#! /bin/bash

#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2021 Joyent, Inc.
#

# This script calls the image_ensure_present action.

ip=$1
image=$2

if [[ -z $ip || -z $image ]]; then
	echo "Usage: $0 ip image_uuid" 1>&2
	exit 1
fi

set -eou pipefail

# zpool param not implemented
json='{
	"task": "image_ensure_present",
	"params": {
		"image_uuid": "'$image'"
	}
}'

echo "Request:"
echo "$json"

echo ""
echo "Response:"
curl -s -X POST \
	-H "Content-Type: application/json" \
	-H "accept: application/json" \
	-d "$json" http://$ip:5309/tasks | json
